export enum CommanGroupKey {
  FREIGHTER_WALLET = "FREIGHTER_WALLET",
  STELLAR_API = "STELLAR_API",
  SOROBAN_API = "SOROBAN_API",
  STELLAR_SOCIALS = "STELLAR_SOCIALS",
  USEFUL_LINKS = "USEFUL_LINKS",
}

export enum CommandKey {
  FREIGHTER_WALLET_LOGIN = "FREIGHTER_WALLET_LOGIN",
  FREIGHTER_WALLET_GET_PUBLIC_KEY = "FREIGHTER_WALLET_GET_PUBLIC_KEY",
  FREIGHTER_WALLET_GET_NETWORK = "FREIGHTER_WALLET_GET_NETWORK",
  FREIGHTER_WALLET_GET_NETWORK_INFO = "FREIGHTER_WALLET_GET_NETWORK_INFO",
  FREIGHTER_WALLET_INSTALL = "FREIGHTER_WALLET_INSTALL",

  STELLAR_API_SEND_PAYMENT = "STELLAR_API_SEND_PAYMENT",
  STELLAR_API_LOAD_ACCOUNT = "STELLAR_API_LOAD_ACCOUNT",
  STELLAR_API_RECENT_PAYMENTS = "STELLAR_API_RECENT_PAYMENTS",

  STELLAR_SOCIALS_X = "STELLAR_SOCIALS_X",
  STELLAR_SOCIALS_DISCORD = "STELLAR_SOCIALS_DISCORD",
  STELLAR_SOCIALS_REDDIT = "STELLAR_SOCIALS_REDDIT",
  STELLAR_SOCIALS_GITHUB = "STELLAR_SOCIALS_GITHUB",
  STELLAR_SOCIALS_LINKEDIN = "STELLAR_SOCIALS_LINKEDIN",

  USEFUL_LINKS_STELLAR_DEV_DOCS = "USEFUL_LINKS_STELLAR_DEV_DOCS",
  USEFUL_LINKS_SOROBAN_DEV_DOCS = "USEFUL_LINKS_SOROBAN_DEV_DOCS",
}
